#ifndef _LANGUAGE_GE_H
#define _LANGUAGE_GE_H
//****************德语***************************//
#define TOOL_TEXT_GE				"Werkzeug"        
#define PREHEAT_TEXT_GE 	        "Vorwärmen"      
#define	MOVE_TEXT_GE				"Bewegen"      
#define HOME_TEXT_GE 		        "Home"       
#define PRINT_TEXT_GE		        "Drucken"       
#define EXTRUDE_TEXT_GE 	        "Extrusion"       
#define LEVELING_TEXT_GE            "Leveling"           
#define AUTO_LEVELING_TEXT_GE       "AutoLevel"       
#define SET_TEXT_GE		       		"Einstellen"            
#define MORE_TEXT_GE                "Mehr"            

#define ADD_TEXT_GE			        "Plus"      
#define DEC_TEXT_GE			        "Minus"  
#define EXTRUDER_1_TEXT_GE		    "Extruder_1"  
#define EXTRUDER_2_TEXT_GE		    "Extruder_2"  
#define HEATBED_TEXT_GE			    "Heizbett"  

#define CLOSE_TEXT_GE				"Schließen"  

#define BACK_TEXT_GE					"Zurück"  
 
#define TOOL_PREHEAT_GE              	"Vorwärmen"                   
#define TOOL_EXTRUDE_GE             	"Extrudieren"               
#define TOOL_MOVE_GE                	"Bewegen"                  
#define TOOL_HOME_GE                	"Home"                
#define TOOL_LEVELING_GE               	"Leveling"              
#define TOOL_AUTO_LEVELING_GE         	"AutoLevel"         
#define TOOL_FILAMENT_GE                "Filament"           
#define TOOL_MORE_GE                    "Mehr"           

#define AXIS_X_ADD_TEXT_GE				"X plus"  
#define AXIS_X_DEC_TEXT_GE				"X minus"  
#define AXIS_Y_ADD_TEXT_GE				"Y plus"  
#define AXIS_Y_DEC_TEXT_GE				"Y minus"  
#define AXIS_Z_ADD_TEXT_GE				"Z plus"  
#define AXIS_Z_DEC_TEXT_GE				"ZZ minus"  
#define TEXT_01MM_GE					"0.1mm" 
#define TEXT_1MM_GE						"1mm" 
#define TEXT_10MM_GE					"10mm"  
    
#define HOME_X_TEXT_GE						"X" 
#define HOME_Y_TEXT_GE						"Y" 
#define HOME_Z_TEXT_GE						"Z" 
#define HOME_ALL_TEXT_GE					"HomeAll"  
#define HOME_STOPMOVE_GE                    "Not Aus"            

#define PAGE_UP_TEXT_GE						"PageUp"     
#define PAGE_DOWN_TEXT_GE					"PageDown"     

#define EXTRUDER_IN_TEXT_GE		      		"In"            
#define EXTRUDER_OUT_TEXT_GE		      	"Aus"           
#define EXTRUDE_1MM_TEXT_GE					"1mm"       
#define EXTRUDE_5MM_TEXT_GE					"5mm"
#define EXTRUDE_10MM_TEXT_GE		        "10mm"   
#define EXTRUDE_LOW_SPEED_TEXT_GE			"Low"      
#define EXTRUDE_MEDIUM_SPEED_TEXT_GE	    "Mittel"      
#define EXTRUDE_HIGH_SPEED_TEXT_GE			"Hoch"      

#define LEVELING_POINT1_TEXT_GE				"PUNKT 1"  
#define LEVELING_POINT2_TEXT_GE				"PUNKT 2"  
#define LEVELING_POINT3_TEXT_GE				"PUNKT 3"  
#define LEVELING_POINT4_TEXT_GE				"PUNKT 4"  
#define LEVELING_POINT5_TEXT_GE				"PUNKT 5"  

#define FILESYS_TEXT_GE						"Dateisystem"  
#define WIFI_TEXT_GE						"WIFI"   
#define FAN_TEXT_GE							"Ventilator"  
#define ABOUT_TEXT_GE						"Über"   
#define BREAK_POINT_TEXT_GE					"Weiter\ndruchen"
#define material_TEXT_GE					"Material\nwechseln"    
#define LANGUAGE_TEXT_GE					"Sprache"  
#define MOTOR_OFF_TEXT_GE					"Motor\nAusschalten" 
#define SHUTDOWN_TEXT_GE					"Abschaltem"
#define X_MODE_TEXT_GE                   	"Druckmodus"
#define EEPROM_SETTINGS_GE					"Eeprom Set"
#define EEPROM_SETTINGS_TITLE_GE            "EEPROM Settings"
#define EEPROM_SETTINGS_REVERT_GE 			"Einstellungen auf standard für die anlage einstellen"
#define EEPROM_REVERT_TIPS_GE				"Einstellungen auf standard für die anlage einstellen?"
#define TOOL_OFFSET_GE				        "T-offset"
#define MOTOR_SETTINGS_GE                   "Motor"

#define U_DISK_TEXT_GE						"USB Stick "     
#define SD_CARD_TEXT_GE						"SD Karte"    
#define WIFI_NAME_TEXT_GE					"WIFI Name:" 
#define WIFI_KEY_TEXT_GE					"Passwort: "    
#define WIFI_IP_TEXT_GE						"IP: " 
#define WIFI_AP_TEXT_GE						"Zustand_AP"  
#define WIFI_STA_TEXT_GE					"Zustand_STA" 
#define WIFI_CONNECTED_TEXT_GE				"verbunden"  
#define WIFI_DISCONNECTED_TEXT_GE			"nicht verbunden"
#define WIFI_EXCEPTION_TEXT_GE				"Modulausnahme"     
#define CLOUD_TEXT_GE						"Cloud-Dienst"   
#define CLOUD_BIND_GE						"CLOUD Binden"   
#define CLOUD_UNBIND_GE						"CLOUD Lösen"     
#define CLOUD_UNBINDING_GE					"CLOUD Entbinden"  
#define CLOUD_DISCONNECTED_GE				"Nicht Verbinden"   
                                                    
#define CLOUD_UNBINDED_GE					"Unbinded"   
#define CLOUD_BINDED_GE						"Binden"    
#define CLOUD_DISABLE_GE					"Deaktivieren"                                                       

#define FAN_ADD_TEXT_GE						"Plus"   
#define FAN_DEC_TEXT_GE						"Minus"   
#define FAN_OPEN_TEXT_GE					"100%"   
#define FAN_HALF_TEXT_GE					"50%"   
#define FAN_CLOSE_TEXT_GE					"Abschalten"   
#define FAN_TIPS1_TEXT_GE					"Ventilator"   
#define FAN_TIPS2_TEXT_GE					"FAN\nClose"  

#define FILAMENT_IN_TEXT_GE					"In"   
#define FILAMENT_OUT_TEXT_GE				"Out"   
#define FILAMENT_EXT0_TEXT_GE				"Extruder 1"  
#define FILAMENT_EXT1_TEXT_GE				"Extruder 2"  
#define FILAMENT_HEAT_TEXT_GE				"Vorwärmen"	 				
#define FILAMENT_STOP_TEXT_GE				"Aufhören"   

#define FILAMENT_CHANGE_TEXT_GE					"Wenn Drucker aufhört,\ndrücken Sie<lade  material>\n oder <beenden material>"

#define FILAMENT_DIALOG_LOAD_HEAT_TIPS_GE		"Fertig vom Filamet In und\n Heizen, bitte warten!"

#define FILAMENT_DIALOG_UNLOAD_HEAT_TIPS_GE		"Bereit zur beenden material \nund Aufheizen, bitte warten!"

#define FILAMENT_DIALOG_LOAD_CONFIRM1_TIPS_GE   "Nachdem das Erhitzen fertig ist, \nlegen Sie bitte die materiale und \ndrücken <OK>, zu beginnen!"

#define FILAMENT_DIALOG_LOAD_CONFIRM2_TIPS_GE   "Bitte legen Sie die materiale \nund drücken Sie <OK>, \num mit dem material zu laden!"

#define FILAMENT_DIALOG_UNLOAD_CONFIRM_TIPS_GE  "Nach Ferigkeit von dem \nErhitzen drücken Sie bitte <OK>, \num zurückzukehren!"

#define FILAMENT_DIALOG_LOADING_TIPS_GE         "material laden, bitte warten Sie, \nbis die material geladen sind"

#define FILAMENT_DIALOG_UNLOADING_TIPS_GE       "Das material wird zurückgesandt. \nWarten Sie, bis das Entladen des \nbeenden materials abgeschlossen ist"

#define FILAMENT_DIALOG_LOAD_COMPLETE_TIPS_GE   "Laden des materialdialogs \nabgeschlossen. Bitte drücken Sie \n<OK>, um zurückzukehren"

#define FILAMENT_DIALOG_UNLOAD_COMPLETE_TIPS_GE "Die Rücksendung ist abgeschlossen. \nBitte drücken Sie <OK>, \num zurückzukehren"


#define FILAMENT_TIPS3_TEXT_GE				"lade  material"  
#define FILAMENT_TIPS4_TEXT_GE				"beenden material  "  
         
#define FILAMENT_TIPS5_TEXT_GE				"Niedrige Temperatur, bitte \nDruckbett vorheizen."
#define FILAMENT_TIPS6_TEXT_GE				"Der material  fertig"

#define PRE_HEAT_EXT_TEXT_GE				"EXTRUDER"  
#define PRE_HEAT_BED_TEXT_GE				"Druckbett"  

#define FILE_LOADING_GE						"File laden......"
#define NO_FILE_AND_CHECK_GE			    "Keine Datei! Bitte SD-Karte \noder USB-Stick einlegen!"
#define NO_FILE_GE					    	"Keine Datei!"

#define EXTRUDER_TEMP_TEXT_GE				"Temperatur"  
#define EXTRUDER_E_LENGTH1_TEXT_GE          "EXTRUDER"   
#define EXTRUDER_E_LENGTH2_TEXT_GE          "EXTRUDER"   
#define EXTRUDER_E_LENGTH3_TEXT_GE          "EXTRUDER"   

#define ABOUT_TYPE_TEXT_GE					"Art: "  
#define ABOUT_VERSION_TEXT_CN				"Firmware: " 
#define ABOUT_WIFI_TEXT_GE					"Wifi: "  

#define PRINTING_OPERATION_GE				"Betrieb"  
#define PRINTING_PAUSE_GE					"Pause" 
#define PRINTING_TEMP_GE					"Temperatur"   
#define PRINTING_CHANGESPEED_GE			    "ChangeSpeed"                    
#define PRINTING_RESUME_GE					"Erneuern"   
#define PRINTING_STOP_GE					"Aufhören"   
#define PRINTING_MORE_GE					"Mehr"   
#define PRINTING_EXTRUDER_GE			    "Extrusion"   
#define PRINTING_MOVE_GE					"Bewegen"   

#define EXTRUDER_SPEED_GE					"Extrusion"   
#define MOVE_SPEED_GE						"Bewegen"   
#define EXTRUDER_SPEED_STATE_GE			    "Extrude"
#define MOVE_SPEED_STATE_GE					"Bewegen" 
#define STEP_1PERCENT_GE					"1%"  
#define STEP_5PERCENT_GE					"5%"
#define STEP_10PERCENT_GE					"10%" 

#define ZOFFSET_GE                                              "Z Offset" 
#define ZOFFSET_INC_GE                                          "Plus"  
#define ZOFFSET_DEC_GE                                          "Minus"  

#define TITLE_READYPRINT_GE						"Bereit Drucken" 
#define TITLE_PREHEAT_GE						"Vorwärmen"  
#define TITLE_MOVE_GE					        "Bewegen"   
#define TITLE_HOME_GE							"Home" 
#define TITLE_EXTRUDE_GE						"Extrusion"   
#define TITLE_LEVELING_GE						"Leveling"   
#define TITLE_SET_GE							"Eistellen" 
#define TITLE_MORE_GE							"Mehr"  
#define TITLE_CHOOSEFILE_GE						"Datei wählen" 

#define TITLE_PRINTING_GE						"Drucken" 
#define TITLE_OPERATION_GE						"OPERATION"  
#define TITLE_ADJUST_GE							"justieren"  
#define	TITLE_WIRELESS_GE						"Netzwerk"   
#define	TITLE_FILAMENT_GE						"Material wechseln" 
#define TITLE_ABOUT_GE							"Über" 
#define TITLE_FAN_GE							"Ventilator" 
#define TITLE_LANGUAGEIT						"Sprache"  
#define TITLE_PAUSE_GE							"Pause"  
#define TITLE_CHANGESPEED_GE				    "ChangeSpeed"
#define TITLE_CLOUD_TEXT_GE				        "Cloud Dienst" 
#define TITLE_DIALOG_CONFIRM_GE				    "Bestätigen" 
#define TITLE_FILESYS_GE						"Dateisystem" 
#define TITLE_ZOFFSET_GE                        "Z Offset" 

#define AUTO_SHUTDOWN_GE					"Auto-off" 

#define MANUAL_SHUTDOWN_GE					"manu-off"

#define DIALOG_CONFIRM_GE					"OK" 
#define DIALOG_CANCLE_GE					"Stornieren" 
#define DIALOG_OK_GE						"OK" 

#define DIALOG_DISABLE_GE					"Disable"  
#define DIALOG_PRINT_MODEL_GE			    "Modell Drucken?"  
#define DIALOG_CANCEL_PRINT_GE		        "Druck aufhören?"  
#define DIALOG_RETRY_GE						"wiederholen" 
#define DIALOG_STOP_GE						"aufhören" 
#define DIALOG_REPRINT_FROM_BREAKPOINT_GE	"Vom BREAKPOINT DRUCKEN?"
#define DIALOG_UNBIND_PRINTER_GE			"Binden Lösen?"
#define DIALOG_ERROR_TIPS1_GE				"Fehler: Keine Datei!Bitte \nSD-Karte oder USB-Stick einlegen!"
#define DIALOG_ERROR_TIPS2_GE				"Fehler: Kommunikation fehlgeschlagen, \nbitte Baudrate oder \nMotherboard-Hardware überprüfen! "
#define DIALOG_ERROR_TIPS3_GE				"Fehler: Der Dateiname oder \nDateipfad ist zu lang!"
#define DIALOG_CLOSE_MACHINE_GE             "Abschalten..."
#define DIALOG_UNBIND_PRINTER_GE            "Binden Lösen?"
#define DIALOG_material_NO_PRESS_GE         "Bitte geben sie material ein!"

#define MOTOR_OFF_XY_TEXT_GE				"XY\ndeaktivieren"
#define FILAMENT_TEXT_GE					"Material\nwechseln"

#define ABOUT_VERSION_TEXT_GE				"Firmware: "
#define DIALOG_FILAMENT_NO_PRESS_GE         "Filament detection switch is not pressed"

#define MACHINE_PARA_GE				"Aufbau"
#define WIFI_RECONNECT_TEXT_GE		"Reconnect"
#define TITLE_LANGUAGE_GE			"Sprache"
#define DIALOG_PRINT_FINISH_GE		"Druck abgeschlossen!"
#define DIALOG_PRINT_TIME_GE		"Druckzeit: "
#define DIALOG_REPRINT_GE			"Erneut drucken"
#define DIALOG_WIFI_ENABLE_TIPS_GE	"The wifi module is being configured\nplease wait a moment....."

#define MESSEGE_PAUSING_GE			"Pause..."
#define MESSEGE_CHANGING_GE 		"Dann geht die lampe wieder los"
#define MESSEGE_UNLOAD_GE			"Wir warten, bis die lampe ausgeladen ist"
#define MESSEGE_WAITING_GE			"Knopf drücken und den druck wiederherstellen"
#define MESSEGE_INSERT_GE			"Lösen sie den lampenschirm ein und drücken sie den knopf"
#define MESSEGE_LOAD_GE				"Warte auf strom..."
#define MESSEGE_PURGE_GE			"Warte, bis die lampe wieder raus ist"
#define MESSEGE_RESUME_GE			"Ich erwarte wiederauffülltes bild"
#define MESSEGE_HEAT_GE				"Man erhitzt die düsen durch knopf"
#define MESSEGE_HEATING_GE			"Warten sie bitte die hitze..."
#define MESSEGE_OPTION_GE			"Presst mehr Oder druckt weiter?"
#define MESSEGE_PURGE_MORE_GE   	"Links"
#define MESSEGE_CONTINUE_PRINT_GE   "Drucke seiten"

#define MODE_INDEX_GE   			"In druckmodus"
#define FULL_CONTROL_GE				"Einhebender typ"
#define AUTO_PARK_GE				"Der zwei-köpfige gang"
#define DUPLICATION_GE				"Im kopiermodus"
#define MIRRORED_GE		  			"Im spiegel"

#define TOOL_OFFSET_TITLE_GE    	"Tool offset"
#define TOOL_X_OFSSET_GE  			"X2 offset"
#define TOOL_Y_OFSSET_GE  			"Y2 offset"
#define TOOL_Z_OFSSET_GE  			"Z2 offset"

#endif